#Requires -Version 5.1
[CmdletBinding(SupportsShouldProcess)]
param(
    [string] $ModuleRoot = $(if ($env:PRIMORDIAL_HOME) { $env:PRIMORDIAL_HOME } else { Join-Path $PSScriptRoot 'PrimordialOS' }),
    [switch] $NoReload,
    [switch] $Force
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

# ─────────────────────────────────────────────────────────────────────────────
# CONSTANTS
# ─────────────────────────────────────────────────────────────────────────────
$COMPILER_VERSION = '1.0.0'
$MODULE_VERSION   = '3.0.0'

$MODULE_FILE      = 'PrimordialOS.psm1'
$MANIFEST_FILE    = 'PrimordialOS.psd1'

$MODULE_PATH      = Join-Path $ModuleRoot $MODULE_FILE
$MANIFEST_PATH    = Join-Path $ModuleRoot $MANIFEST_FILE
$BACKUP_PATH      = Join-Path $ModuleRoot ("PrimordialOS_backup_{0:yyyyMMdd_HHmmss}.psm1" -f (Get-Date))

$STRIP_ANCHORS = @(
    '# AUTO-GENERATED BY Compile-PrimordialOS',
    '# REGION: HEADER',
    '# REGION: MEMORY',
    '# REGION: DIAGNOSTIC',
    '# REGION: ROUTER',
    '# REGION: DASHBOARD',
    '# REGION: HUD',
    '# REGION: PROPHECY',
    '# REGION: AGENTS',
    '# REGION: LOOPS',
    '# REGION: EXPORTS'
)

# ─────────────────────────────────────────────────────────────────────────────
# PLACEHOLDER BLOCKS (for missing subsystems)
# ─────────────────────────────────────────────────────────────────────────────

$BLOCK_HEADER = @'
# REGION: HEADER
# Placeholder header block
'@

$BLOCK_MEMORY = @'
# REGION: MEMORY
# Placeholder memory block
'@

$BLOCK_DIAGNOSTIC = @'
# REGION: DIAGNOSTIC
function Invoke-PrimordialDiagnostic {
    return @{ Overall = "HEALTHY"; Failed = @() }
}
'@

$BLOCK_ROUTER = @'
# REGION: ROUTER
function Invoke-PrimordialRouter { }
function Register-PrimordialRoute { }
'@

$BLOCK_DASHBOARD = @'
# REGION: DASHBOARD
function Show-PrimordialDashboard {
    Write-Host "PrimordialOS Dashboard Loaded" -ForegroundColor Cyan
}
'@

$BLOCK_HUD = @'
# REGION: HUD
function Show-PrimordialHUD {
    Write-Host "HUD online" -ForegroundColor Cyan
}
'@

$BLOCK_PROPHECY = @'
# REGION: PROPHECY
function Invoke-ProphecyEngine { }
function Add-ProphecyOracle { }
function Get-ProphecyHistory { }
'@

# ─────────────────────────────────────────────────────────────────────────────
# REAL BLOCKS (from your attached document)
# ─────────────────────────────────────────────────────────────────────────────

$BLOCK_AGENTS = @'
# REGION: AGENTS
function Stop-PrimordialAgent {
    [CmdletBinding()]
    param([Parameter(Mandatory)][string]$Name)
    $key = $Name.ToLower()
    if ($script:AGENT_REGISTRY.Contains($key)) {
        $script:AGENT_REGISTRY.Remove($key)
        Write-Host " [AGENT] Stopped: $Name" -ForegroundColor Yellow
    } else {
        Write-Host " [AGENT] Not found: $Name" -ForegroundColor Red
    }
}

function Get-PrimordialAgents {
    if ($script:AGENT_REGISTRY.Count -eq 0) {
        Write-Host " [AGENT] No active agents." -ForegroundColor Yellow; return
    }
    Write-Host "`n == ACTIVE AGENTS ==" -ForegroundColor Cyan
    $script:AGENT_REGISTRY.GetEnumerator() | ForEach-Object {
        $ag = $_.Value
        $age = (Get-Date) - $ag.StartTime
        $ageStr = "{0:D2}:{1:D2}:{2:D2}" -f [int]$age.TotalHours,$age.Minutes,$age.Seconds
        Write-Host (" [{0}] {1,-15} | {2,-10} | up:{3} | cycles:{4}" -f
            $ag.Status,$ag.Name,$ag.Role,$ageStr,$ag.Cycles) -ForegroundColor White
    }
    Write-Host ""
}

function Invoke-AgentPulse {
    $script:AGENT_REGISTRY.GetEnumerator() | ForEach-Object {
        $_.Value.Cycles++
        $_.Value.LastPulse = Get-Date
    }
}

Set-Alias -Name agents -Value Get-PrimordialAgents -Scope Global -Force
Set-Alias -Name spawn -Value Start-PrimordialAgent -Scope Global -Force
'@

$BLOCK_LOOPS = @'
# REGION: LOOPS
$script:LOOP_REGISTRY = [ordered]@{}

function Start-PrimordialLoop {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)][string]$Name,
        [int]$IntervalSeconds = 5,
        [scriptblock]$Action = { },
        [int]$MaxCycles = 0
    )
    $key = $Name.ToLower()
    if ($script:LOOP_REGISTRY.Contains($key)) {
        Write-Host " [LOOP] '$Name' already running." -ForegroundColor Yellow; return
    }

    $actStr = $Action.ToString()
    $job = Start-Job -Name "PrimordialLoop_$Name" -ScriptBlock {
        param($interval,$maxC,$actStr)
        $act = [scriptblock]::Create($actStr)
        $c = 0
        while ($maxC -eq 0 -or $c -lt $maxC) {
            try { & $act } catch { }
            $c++
            Start-Sleep -Seconds $interval
        }
    } -ArgumentList $IntervalSeconds,$MaxCycles,$actStr

    $loop = [PSCustomObject]@{
        Name = $Name; IntervalSeconds = $IntervalSeconds
        Action = $Action; MaxCycles = $MaxCycles
        Cycles = 0; Status = 'RUNNING'
        StartTime = Get-Date; Job = $job
    }
    $script:LOOP_REGISTRY[$key] = $loop
    Write-Host (" [LOOP] Started: {0} (every {1}s, job #{2})" -f $Name,$IntervalSeconds,$job.Id) -ForegroundColor Green
    return $loop
}

function Stop-PrimordialLoop {
    [CmdletBinding()]
    param([Parameter(Mandatory)][string]$Name)
    $key = $Name.ToLower()
    if ($script:LOOP_REGISTRY.Contains($key)) {
        $lp = $script:LOOP_REGISTRY[$key]
        if ($lp.Job) {
            Stop-Job $lp.Job -ErrorAction SilentlyContinue
            Remove-Job $lp.Job -ErrorAction SilentlyContinue
        }
        $script:LOOP_REGISTRY.Remove($key)
        Write-Host " [LOOP] Stopped: $Name" -ForegroundColor Yellow
    } else {
        Write-Host " [LOOP] Not found: $Name" -ForegroundColor Red
    }
}

function Get-PrimordialLoops {
    if ($script:LOOP_REGISTRY.Count -eq 0) {
        Write-Host " [LOOP] No active loops." -ForegroundColor Yellow; return
    }
    Write-Host "`n == ACTIVE LOOPS ==" -ForegroundColor Cyan
    $script:LOOP_REGISTRY.GetEnumerator() | ForEach-Object {
        $lp = $_.Value
        Write-Host (" [{0}] {1,-15} | every {2}s | job:{3}" -f
            $lp.Status,$lp.Name,$lp.IntervalSeconds,$lp.Job.Id) -ForegroundColor White
    }
    Write-Host ""
}

function Stop-AllPrimordialLoops {
    [CmdletBinding()]
    param()
    $keys = @($script:LOOP_REGISTRY.Keys)
    foreach ($k in $keys) { Stop-PrimordialLoop -Name $k }
    Write-Host " [LOOP] All loops stopped." -ForegroundColor Yellow
}

Set-Alias -Name loops -Value Get-PrimordialLoops -Scope Global -Force
'@

$BLOCK_EXPORTS = @'
# REGION: EXPORTS
function Export-PrimordialState {
    [CmdletBinding()]
    param([string]$Path = (Join-Path $PSScriptRoot ("PrimordialState_{0:yyyyMMdd_HHmmss}.json" -f (Get-Date))))

    $state = [ordered]@{
        ExportedAt = (Get-Date).ToString('u')
        Version = $script:PRIMORDIAL_VERSION
        SessionID = $script:SESSION_ID
        BootTime = $script:BOOT_TIME.ToString('u')
        Memory = $script:PRIMORDIAL_MEMORY
        Agents = @($script:AGENT_REGISTRY.GetEnumerator() | ForEach-Object {
            [ordered]@{ Name=$_.Value.Name; Role=$_.Value.Role; Status=$_.Value.Status; Cycles=$_.Value.Cycles }
        })
        Loops = @($script:LOOP_REGISTRY.GetEnumerator() | ForEach-Object {
            [ordered]@{ Name=$_.Value.Name; IntervalSeconds=$_.Value.IntervalSeconds; Status=$_.Value.Status }
        })
        Routes = @($script:ROUTER_TABLE.Keys)
        ProphecyLog = @($script:PROPHECY_HISTORY | ForEach-Object {
            [ordered]@{ CycleID=$_.CycleID; Query=$_.Query; Oracle=$_.Oracle; At=$_.Timestamp.ToString('u') }
        })
    }
    $state | ConvertTo-Json -Depth 10 | Set-Content -Path $Path -Encoding UTF8 -Force
    Write-Host " [EXPORT] State saved -> $Path" -ForegroundColor Green
    return $Path
}

$script:PUBLIC_FUNCTIONS = @(
    'Invoke-PrimordialDiagnostic','Invoke-PrimordialRouter','Register-PrimordialRoute',
    'Show-PrimordialDashboard','Show-PrimordialHUD',
    'Invoke-ProphecyEngine','Add-ProphecyOracle','Get-ProphecyHistory',
    'Start-PrimordialAgent','Stop-PrimordialAgent','Get-PrimordialAgents','Invoke-AgentPulse',
    'Start-PrimordialLoop','Stop-PrimordialLoop','Get-PrimordialLoops','Stop-AllPrimordialLoops',
    'Export-PrimordialState'
)

Export-ModuleMember -Function $script:PUBLIC_FUNCTIONS -Alias '*'
'@

# ─────────────────────────────────────────────────────────────────────────────
# MANIFEST TEMPLATE
# ─────────────────────────────────────────────────────────────────────────────

$MANIFEST_CONTENT = @"
@{
    ModuleVersion = '$MODULE_VERSION'
    GUID = 'a1b2c3d4-e5f6-7890-abcd-ef1234567890'
    Author = 'PrimordialOS Compiler'
    Description = 'PrimordialOS unified runtime module'
    PowerShellVersion = '5.1'
    RootModule = '$MODULE_FILE'
    FunctionsToExport = '*'
    AliasesToExport = '*'
    PrivateData = @{ PSData = @{ Tags = @('PrimordialOS','Terminal','Runtime') } }
}
"@

# ─────────────────────────────────────────────────────────────────────────────
# COMPILER HELPERS
# ─────────────────────────────────────────────────────────────────────────────

function Get-CleanHeader {
    param([string]$FilePath)
    if (-not (Test-Path $FilePath)) { return '' }
    $lines = Get-Content $FilePath -Encoding UTF8
    $cutIndex = -1
    for ($i = 0; $i -lt $lines.Count; $i++) {
        foreach ($anchor in $STRIP_ANCHORS) {
            if ($lines[$i] -match [regex]::Escape($anchor)) {
                $cutIndex = $i; break
            }
        }
        if ($cutIndex -ge 0) { break }
    }
    if ($cutIndex -le 0) { return '' }
    return ($lines[0..($cutIndex - 1)] -join "`n")
}

function Test-ScriptSyntax {
    param([string]$FilePath)
    $errors = $null
    $tokens = $null
    [System.Management.Automation.Language.Parser]::ParseFile($FilePath, [ref]$tokens, [ref]$errors) | Out-Null
    if ($errors.Count -gt 0) {
        $errors | ForEach-Object {
            Write-Host ("Syntax: Line {0} — {1}" -f $_.Extent.StartLineNumber, $_.Message) -ForegroundColor Red
        }
        return $false
    }
    return $true
}

function Write-Manifest {
    param([string]$Path)
    if (-not (Test-Path $Path)) {
        $MANIFEST_CONTENT | Set-Content -Path $Path -Encoding UTF8 -Force
        Write-Host "Manifest written: $Path" -ForegroundColor Green
    } else {
        Write-Host "Manifest already exists — skipping" -ForegroundColor Yellow
    }
}

# ─────────────────────────────────────────────────────────────────────────────
# MAIN COMPILER
# ─────────────────────────────────────────────────────────────────────────────

Write-Host "PrimordialOS Compiler v$COMPILER_VERSION" -ForegroundColor Cyan
Write-Host "Target: $MODULE_PATH" -ForegroundColor DarkCyan

if (-not (Test-Path $ModuleRoot)) {
    New-Item -ItemType Directory -Path $ModuleRoot -Force | Out-Null
    Write-Host "Created module directory: $ModuleRoot" -ForegroundColor Green
}

if (Test-Path $MODULE_PATH) {
    Copy-Item -Path $MODULE_PATH -Destination $BACKUP_PATH -Force
    Write-Host "Backup saved: $BACKUP_PATH" -ForegroundColor Green
} else {
    Write-Host "No existing module found — creating fresh" -ForegroundColor Yellow
}

$preamble = Get-CleanHeader -FilePath $MODULE_PATH
if (-not $preamble) {
    $preamble = @"
#Requires -Version 5.1
<#
.SYNOPSIS PrimordialOS — Unified Runtime Module
.VERSION $MODULE_VERSION
.NOTES Built by Compile-PrimordialOS.ps1
#>
"@
}

$blocks = @(
    $preamble,
    $BLOCK_HEADER,
    $BLOCK_MEMORY,
    $BLOCK_DIAGNOSTIC,
    $BLOCK_ROUTER,
    $BLOCK_DASHBOARD,
    $BLOCK_HUD,
    $BLOCK_PROPHECY,
    $BLOCK_AGENTS,
    $BLOCK_LOOPS,
    $BLOCK_EXPORTS
)

$assembled = $blocks -join "`n`n"

[System.IO.File]::WriteAllText($MODULE_PATH, $assembled, [System.Text.Encoding]::UTF8)
Write-Host "Module written: $MODULE_PATH" -ForegroundColor Green

Write-Manifest -Path $MANIFEST_PATH

$syntaxOK = Test-ScriptSyntax -FilePath $MODULE_PATH
if ($syntaxOK) {
    Write-Host "Syntax clean — no errors detected" -ForegroundColor Green
} else {
    Write-Host "Syntax errors found — module may not load" -ForegroundColor Red
}

if (-not $NoReload) {
    Remove-Module PrimordialOS -ErrorAction SilentlyContinue
    Import-Module $MODULE_PATH -Force -Global -DisableNameChecking
    Write-Host "Module loaded: PrimordialOS v$MODULE_VERSION" -ForegroundColor Green
}

Write-Host "PrimordialOS compiler finished." -ForegroundColor Cyan
