import React, { useState } from 'react';
import { 
  Sparkles, Calendar, CheckCircle2, Circle, ArrowRight, Zap, 
  GitCommit, Layers, Flame, Brain, Shield, Rocket, Clock 
} from 'lucide-react';

interface ChangelogRoadmapPageProps {
  onNavigate?: (tab: string) => void;
}

export const ChangelogRoadmapPage: React.FC<ChangelogRoadmapPageProps> = ({ onNavigate }) => {
  const [activeView, setActiveView] = useState<'changelog' | 'roadmap'>('changelog');

  const changelog = [
    {
      version: 'v1.0.0 — Official Launch Edition',
      date: 'August 2026',
      badge: 'Current Release',
      badgeColor: 'bg-emerald-500/20 text-emerald-300 border-emerald-500/30',
      highlights: [
        '🎙️ ElevenLabs 241ms streaming voice synthesis (eleven_flash_v2_5) with barge-in interruption.',
        '🪬 Deterministic Procedural Sigil Engine generating cryptographic vector emblems via SHA-256.',
        '⚡ 10 Nuclear Viral Growth Mechanics (leveling XP, streaks, seasonal leaderboards, boost events).',
        '🧬 Native Viral Algorithm Engine with realtime K-Factor modeling and 2.5× Hyper-Drive surges.',
        '🔮 Active Creator AI Studio (v2.0) with 5-Pulse automated script generation and FTC compliance.',
        '💳 Self-Hosted $0/mo SaaS Billing & Subscription Engine (4 Tiers, 14-day trials, promo codes).',
        '🔗 Self-Hosted Affiliate & Referral Engine with 30-day attribution cookies and 5-tier commissions.',
        '🛡️ Living Breathing Wealth Vault background scaling dynamically with net worth and XP tier.',
      ],
    },
    {
      version: 'v0.9.0 Beta — Voice & Vault Integration',
      date: 'July 2026',
      badge: 'Beta Phase',
      badgeColor: 'bg-purple-500/20 text-purple-300 border-purple-500/30',
      highlights: [
        'Implemented ACID SQLite transaction ledger with Write-Ahead Logging (WAL).',
        'Added Debt Avalanche payoff calculator and dynamic budget shields.',
        'Added initial MoneyOS chat brain with ACID financial commands.',
        'Created Command Center overview dashboard and living vault morph themes.',
      ],
    },
    {
      version: 'v0.8.0 Alpha — Core Architecture Prototype',
      date: 'June 2026',
      badge: 'Alpha Prototype',
      badgeColor: 'bg-slate-800 text-slate-400 border-slate-700',
      highlights: [
        'Built initial user authentication, JWT session management, and role-based access.',
        'Established modular multi-agent backend architecture.',
        'Implemented basic crypto ledger and synthetic yield simulator.',
      ],
    },
  ];

  const roadmap = [
    {
      quarter: 'Q4 2026',
      title: 'Mobile PWA & Real-Time Push Telemetry',
      status: 'In Development',
      statusColor: 'text-amber-400 border-amber-500/30 bg-amber-500/10',
      items: [
        'Full Progressive Web App (PWA) with offline financial vault caching.',
        'Real-time push notifications for commission payouts, streak milestones, and surge events.',
        'Native iOS & Android home screen widget displaying live procedural sigils.',
      ],
    },
    {
      quarter: 'Q1 2027',
      title: 'Automated Bank Ingestion (Plaid & Dwolla ACH)',
      status: 'Planned',
      statusColor: 'text-sky-400 border-sky-500/30 bg-sky-500/10',
      items: [
        'Direct bank account linking via Plaid API for live transaction syncing.',
        'Automated next-day ACH commission payouts directly to bank accounts via Dwolla.',
        'Real-time multi-currency exchange rate converters.',
      ],
    },
    {
      quarter: 'Q2 2027',
      title: 'Multi-Chain Crypto Ledger & Solana/Ethereum Vaults',
      status: 'Planned',
      statusColor: 'text-purple-400 border-purple-500/30 bg-purple-500/10',
      items: [
        'Non-custodial Web3 wallet integration (Phantom & MetaMask).',
        'On-chain commission settlements in USDC / SOL.',
        'Procedural Sigil NFT minting on Solana for verified Diamond tier creators.',
      ],
    },
    {
      quarter: 'Q3 2027',
      title: 'Autonomous AI Swarm Co-Pilot 2.0',
      status: 'Research Phase',
      statusColor: 'text-rose-400 border-rose-500/30 bg-rose-500/10',
      items: [
        'Autonomous outbound email follow-ups to referred users on creator behalf.',
        'Personalized daily voice podcasts generated by MoneyOS reviewing your weekly cashflow.',
        'Multi-agent collaborative wealth syndicates with automated profit distribution.',
      ],
    },
  ];

  return (
    <div className="max-w-4xl mx-auto px-4 py-10 space-y-10 font-sans text-slate-200 animate-fadeIn">
      {/* Header */}
      <div className="text-center space-y-4 max-w-2xl mx-auto">
        <div className="inline-flex items-center gap-2 px-3.5 py-1.5 rounded-full bg-plug-accent/15 border border-plug-accent/30 text-plug-accent text-xs font-mono font-bold tracking-wider uppercase">
          <Rocket className="w-3.5 h-3.5" />
          Product Evolution & Strategic Direction
        </div>
        <h1 className="text-4xl sm:text-5xl font-black text-white tracking-tight">
          Changelog & <span className="text-plug-accent">Roadmap</span>
        </h1>
        <p className="text-base text-slate-400 leading-relaxed">
          Track new features, architectural upgrades, and our upcoming 2026–2027 development milestones.
        </p>

        {/* View Toggle */}
        <div className="inline-flex p-1 bg-slate-900 border border-slate-800 rounded-2xl font-mono text-xs">
          <button
            onClick={() => setActiveView('changelog')}
            className={`px-5 py-2 rounded-xl font-bold transition-all ${
              activeView === 'changelog'
                ? 'bg-plug-accent text-plug-dark shadow-md'
                : 'text-slate-400 hover:text-white'
            }`}
          >
            📋 Version Changelog
          </button>
          <button
            onClick={() => setActiveView('roadmap')}
            className={`px-5 py-2 rounded-xl font-bold transition-all ${
              activeView === 'roadmap'
                ? 'bg-plug-accent text-plug-dark shadow-md'
                : 'text-slate-400 hover:text-white'
            }`}
          >
            🚀 Future Roadmap
          </button>
        </div>
      </div>

      {/* CHANGELOG VIEW */}
      {activeView === 'changelog' && (
        <div className="space-y-8 animate-fadeIn">
          {changelog.map((entry, idx) => (
            <div
              key={idx}
              className="p-6 sm:p-8 rounded-3xl bg-slate-900 border border-slate-800 space-y-4 shadow-xl"
            >
              <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2 border-b border-slate-800 pb-4">
                <div>
                  <span className={`px-2.5 py-0.5 rounded-full text-[10px] font-mono font-bold border ${entry.badgeColor}`}>
                    {entry.badge}
                  </span>
                  <h3 className="text-xl font-black text-white mt-1.5">{entry.version}</h3>
                </div>
                <span className="text-xs font-mono text-slate-400 flex items-center gap-1">
                  <Calendar className="w-3.5 h-3.5" />
                  {entry.date}
                </span>
              </div>

              <ul className="space-y-2 text-xs sm:text-sm text-slate-300">
                {entry.highlights.map((item, hIdx) => (
                  <li key={hIdx} className="flex items-start gap-2.5">
                    <CheckCircle2 className="w-4 h-4 text-emerald-400 shrink-0 mt-0.5" />
                    <span>{item}</span>
                  </li>
                ))}
              </ul>
            </div>
          ))}
        </div>
      )}

      {/* ROADMAP VIEW */}
      {activeView === 'roadmap' && (
        <div className="space-y-6 animate-fadeIn">
          {roadmap.map((item, idx) => (
            <div
              key={idx}
              className="p-6 sm:p-8 rounded-3xl bg-slate-900 border border-slate-800 space-y-4 shadow-xl"
            >
              <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2 border-b border-slate-800 pb-4">
                <div>
                  <span className={`px-2.5 py-0.5 rounded-full text-[10px] font-mono font-bold border ${item.statusColor}`}>
                    {item.status}
                  </span>
                  <h3 className="text-xl font-black text-white mt-1.5">{item.quarter}: {item.title}</h3>
                </div>
              </div>

              <ul className="space-y-2 text-xs sm:text-sm text-slate-300">
                {item.items.map((subItem, sIdx) => (
                  <li key={sIdx} className="flex items-start gap-2.5">
                    <Circle className="w-3.5 h-3.5 text-plug-accent shrink-0 mt-1 fill-current" />
                    <span>{subItem}</span>
                  </li>
                ))}
              </ul>
            </div>
          ))}
        </div>
      )}
    </div>
  );
};
export default ChangelogRoadmapPage;
