import { execSync } from "child_process";
import fs from "fs";
import path from "path";
import { writeLedgerEntry } from "../ledger/write-ledger-entry.js";

export function generateDiff({ notes = "", environment = "dev" } = {}) {
  const migrationsDir = path.resolve("primordiaos", "moneyplughub", "migrations");
  if (!fs.existsSync(migrationsDir)) {
    fs.mkdirSync(migrationsDir, { recursive: true });
  }

  const timestamp = new Date().toISOString().replace(/[-:TZ.]/g, "").slice(0, 14);
  const diffFileName = `${timestamp}_diff.sql`;
  const diffFilePath = path.join(migrationsDir, diffFileName);

  console.log("? Calculating schema diff with Supabase CLI...");
  try {
    const diff = execSync("npx supabase db diff --schema public", {
      encoding: "utf8",
      stdio: ["pipe", "pipe", "inherit"]
    });

    if (!diff.trim()) {
      console.log("?? Schema is clean. No diff detected.");
      return null;
    }

    fs.writeFileSync(diffFilePath, diff, "utf8");
    console.log(`? Migration generated: ${diffFilePath}`);

    const ledgerEntry = writeLedgerEntry({
      environment,
      generator: "supabase-cli",
      diffFile: diffFilePath,
      notes: notes || "Automated diff generated by PrimordiaOS Diff Engine"
    });

    return { version: timestamp, diffFile: diffFilePath, ledgerEntry };
  } catch (error) {
    console.error("? Diff generation failed:", error.message);
    throw error;
  }
}
